kind: Service
apiVersion: v1
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None # for headless service there is no cluster IP
  selector:
    app: mysql
    tier: database
    project: expense
    environment: dev
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306