apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: database
    project: expense
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
      project: expense
      environment: dev
  template:
    metadata:
      labels:
        app: mysql
        tier: database
        project: expense
        environment: dev
    spec: 
      containers:
      - name: mysql
        image: meerjan/mysql:v1