apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: database
    project: expense
    environment: dev
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port