apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: database
      project: expense
      environment: dev # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: mysql
        tier: database
        project: expense
        environment: dev
    spec:
      containers:
      - name: mysql
        image: meerjan/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mysql-ebs-sc"
      resources:
        requests:
          storage: 2Gi